name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày một lần vào 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/cogi2996/mif_nextjs.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
