name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày một lần vào 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  sync:
   permissions:
      contents: write
  runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/cogi2996/mif_nextjs.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/NguyenChiThannh/mif_nextjs.git main
  deploy:
    needs: sync  # Chỉ chạy khi job sync hoàn thành
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --prod --token $VERCEL_TOKEN
